# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    "home".device = "/dev/disk/by-uuid/f4bc8010-1223-49e8-93d2-4ffd9ad7567a";
    "swap".device = "/dev/disk/by-uuid/dce7ec52-e57d-4456-a197-3e9c0a203128";
    "root".device = "/dev/disk/by-uuid/c044f534-4a1a-4d90-8165-435ad6cf1198";
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7b747016-aa2d-49d2-bc3c-41cfc88e56db";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ED73-CB6A";
      fsType = "vfat";
      options = [ "fmask=0777" "dmask=0777" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/EDC7-4596";
      fsType = "vfat";
      options = [ "fmask=0777" "dmask=0777" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/25ea2366-0475-47e7-8545-c45481c7d9ca";
      fsType = "ext4";
    };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/90cb7f64-77d1-4ee8-984b-ac334d458bb8"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
