keys:
  - &masterkey age1adevcspxqgfpdpgsyz3am6efaq3sms99qx6nga2rm2kvejs8tfhq4698dd
creation_rules:
  - path_regex: kahlenden/[^/]+\.(yaml|json|env|ini|bin)$
    key_groups:
    - age:
      - *masterkey
